var lan_zh = {
  lan:"中文",
  name:"名称",
  product:"商品",
  serial_number:"编号",
  in_put:"入库",
  out_put:"出库",
  company:"公司",

  address:"地址",
  out_in_put:"出入库",
  inventory:"库存",
  loading:"正在加载",
  load_success:"登陆成功",
  load_fail:"登陆失败",
  success: "成功",
  fail: "失败",
  shop:"店铺",
  missing_data:"数据不完整",
  input_company_name:"请输入公司名称",
  no_company: "请先创建或加入一家公司.",
  company_no_check: "请联系您的公司管理员审核您的加入申请.",
  input_no: "请输入编号",
  input_name: "请输入名称",
  input_price: "请输入价格",
  input_address:"请输入地址",
  price:"价格",
  submit:"提交",
  submiting:"提交中...",
  submit_fail:"提交失败",
  cant_more:"出库数量不能大于库存数量!",
  quantity:"数量",
  enter_quantity:"请输入数量",
  current:"当前",
  no_data:"无数据",
  cargo_position:"货位",
  
  system_prompt:"系统提示",
  click_return:"点击返回",

  failed_query:"查询失败！",
  
  get_success:"获取成功",
  get_fail:"获取失败",
  
  request_success:"请求成功",
  request_fail:"请求失败",
  
  uploading:"正在上传",
  img_upload_success:"图片上传成功",
  img_upload_fail:"图片上传失败",
  
  hint:"提示",
  cancel:"取消",
  search:"搜索",
  creating:"生成中...",
  equipment_get_fail:"获取设备信息失败",
  close:"关闭",

  settings: "设置",
  setting_success:"设置成功",

  bar_code:"条码",
  bar_code_error:"条码错误!",


  index_logbtn:"登录",
  index_check_pending:"待审核",
  index_no_company_name:"请补充公司信息",
  index_in_shop:"进入店铺",

  out_put_type:"类型",
  out_put_warehouse:"仓库",
  out_put_position:"仓位",

  warehouse: "仓库",
  warehouse_add:"增加仓库",
  warehouse_detail:"仓库明细",

  position_navigation_bar_title:"条码库存管理",
  position_search:"查找仓位",
  position_modify: "修改仓位",
  position_modify_success: "修改仓位成功",
  position_modify_fail: "修改仓位失败",
  position_add:"增加仓位",
  position_add_success:"添加仓位成功",
  position_add_fail: "添加仓位失败",
  position_list:"仓位列表",
  position_get_list:"获取仓位列表",
  position_get_list_success:'仓位列表获取成功',
  position_get_list_fail: '仓位列表获取失败',
  position_all:"所有仓位",
  position_qrcode: "仓位二维码",

  product_list:"产品列表",
  product_inventory:"产品库存",
  product_add: "增加产品",
  product_add_success:"添加商品成功",
  product_add_fail: "添加商品失败",
  product_get_loading:"正在获取商品数据",
  product_get_success:"产品获取成功",
  product_get_fail:"产品获取失败",
  product_scan:"扫产品",
  Please_enter_a_barcode_name:"请输入 条码/名称",
  Product_existed:"商品已存在！",

  scan:"扫码",
  scan_product_fail:"产品不存在!",

  qrcode:"二维码",
  qrcode_error:"二维码错误",
  qrcode_generator:"二维码生成器",
  qrcode_goods_shelf:"货架二维码",
  qrcode_goods_shelf_info1:"请点击二维码进行保存,打印并张贴到对应货架",

  check:"检查",
  checking:"检查中...",
  check_completed:"检查完成",
  check_fail:"检查失败,请稍后重试",

  check_company_name_reject:"该公司已被其他人注册,您可以申请加入公司或更换其他公司名称",
  check_company_name_pass:"该公司名可用",

  apply_join:"申请加入",
  regist:"确认注册",

  setting_company:"请设置公司",

  shop_modify:"修改店铺",
  shop_modify_success:"修改店铺成功",
  shop_modify_fail:"修改店铺失败",
  shop_add:"增加店铺",
  shop_add_success:"添加店铺成功",
  shop_add_fail: "添加店铺失败",
  shop_loading:"正在获取门店数据",
  shop_get_success:"门店获取成功",
  shop_get_fail: "门店获取失败",
  

  store:"仓库",
  store_modify: "修改仓库",
  store_modify_success: "修改仓库成功",
  store_modify_fail: "修改仓库失败",
  store_add:"添加仓库",
  store_add_success:"添加仓库成功",
  store_add_fail:"添加仓库失败",
  store_load_local:"获取本店仓库列表",
  store_loading:"正在获取仓库数据",
  store_load_error1:"该仓库不在本店铺,请切换店铺!",
  store_all:"所有仓库",

  shelf_distribution:"货架分布",
  warehouse_distribution:"仓库分布",
  shop_distribution:"店铺分布",

  setting_tabs: ["个人", "公司", "店铺", "岗位"],
  no_result:"无结果",
  this_warehouse:"本仓库",
  this_position: "本货架",
  no_data: "无数据",
  this_position:"本货架",
  audit:"审核",
  staffing:"分配人员",
  add:"增加",
  remove:"移除"


}

module.exports = lan_zh;